name: SonarQube Analysis

on:
 pull_request:
  types:
    - closed   # <=== here we have defined pull request type merged

jobs:
  on-merge: if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'  # <=== here we have defined branch name

runs-on: ubuntu-latest

steps:
- name: Check out the repository
  uses: actions/checkout@v3

- name: echo creds
  run: |
    echo "pr Number= ${{ github.event.pull_request.number }}"
  shell: bash

- name: SonarQube Scan
  uses: sonarsource/sonarqube-scan-action@v4.0.0
  env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        # <=== Sonar Token in secrets
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # <=== Sonar Host Server Name
  with:
      projectBaseDir: .
      args: >
        -Dsonar.projectKey=${{ inputs.project_key }}
        -Dsonar.scm.provider=git
        -Dsonar.analysis.analysisNumber="pr-${{ github.event.pull_request.number }}"  # <=== Extra param to be used in analysis