name: SonarQube Analysis

on:
  pull_request:
    types:
      - closed

jobs:
  on-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: echo creds
        run: |
          echo "pr Number= ${{ github.event.pull_request.number }}"
        shell: bash

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey="${GITHUB_REPOSITORY##*/}"
            -Dsonar.scm.provider=git
            -Dsonar.analysis.analysisNumber="pr-${{ github.event.pull_request.number }}"
            -Dsonar.exclusions=**/*.java